service: integration

plugins:
    - serverless-plugin-typescript
    - serverless-offline
    - serverless-dynamodb-local

provider:
    name: aws
    runtime: nodejs14.x
    region: ap-southeast-2
    profile: "tabin-nipoon"
    stage: ${opt:stage, 'dev'}
    iam:
        role:
            statements:
                - Effect: "Allow"
                  Action:
                      - "dynamodb:Query"
                  Resource:
                      - "arn:aws:dynamodb:ap-southeast-2:319846238176:table/Restaurant-${self:custom.environmentVars.${self:provider.stage}.STAGE_CODE}-${self:provider.stage}"
                      - "arn:aws:dynamodb:ap-southeast-2:319846238176:table/IntegrationMapping-${self:custom.environmentVars.${self:provider.stage}.STAGE_CODE}-${self:provider.stage}/index/byRestaurantIdByIntegrationType"
                - Effect: "Allow"
                  Action:
                      - "dynamodb:PutItem"
                  Resource:
                      - "arn:aws:dynamodb:ap-southeast-2:319846238176:table/IntegrationMapping-${self:custom.environmentVars.${self:provider.stage}.STAGE_CODE}-${self:provider.stage}"
                      - "arn:aws:dynamodb:ap-southeast-2:319846238176:table/Category-${self:custom.environmentVars.${self:provider.stage}.STAGE_CODE}-${self:provider.stage}"
                      - "arn:aws:dynamodb:ap-southeast-2:319846238176:table/Product-${self:custom.environmentVars.${self:provider.stage}.STAGE_CODE}-${self:provider.stage}"
                      - "arn:aws:dynamodb:ap-southeast-2:319846238176:table/ModifierGroup-${self:custom.environmentVars.${self:provider.stage}.STAGE_CODE}-${self:provider.stage}"
                      - "arn:aws:dynamodb:ap-southeast-2:319846238176:table/Modifier-${self:custom.environmentVars.${self:provider.stage}.STAGE_CODE}-${self:provider.stage}"
                      - "arn:aws:dynamodb:ap-southeast-2:319846238176:table/CategoryProductLink-${self:custom.environmentVars.${self:provider.stage}.STAGE_CODE}-${self:provider.stage}"
                      - "arn:aws:dynamodb:ap-southeast-2:319846238176:table/ProductModifierGroupLink-${self:custom.environmentVars.${self:provider.stage}.STAGE_CODE}-${self:provider.stage}"
                      - "arn:aws:dynamodb:ap-southeast-2:319846238176:table/ModifierGroupModifierLink-${self:custom.environmentVars.${self:provider.stage}.STAGE_CODE}-${self:provider.stage}"
                - Effect: "Allow"
                  Action:
                      - "secretsmanager:GetSecretValue"
                  Resource:
                      - "arn:aws:secretsmanager:ap-southeast-2:319846238176:secret:prod/shift8/api_config-yxr8s6"
                      - "arn:aws:secretsmanager:ap-southeast-2:319846238176:secret:prod/shift8/api_token-1BVaye"

functions:
    import-menu:
        name: integration-import-menu-${self:provider.stage}
        handler: src/handlers/importMenu.handler
        timeout: 120
        environment:
            RESTAURANT_TABLE_NAME: "Restaurant-${self:custom.environmentVars.${self:provider.stage}.STAGE_CODE}-${self:provider.stage}"
            CATEGORY_TABLE_NAME: "Category-${self:custom.environmentVars.${self:provider.stage}.STAGE_CODE}-${self:provider.stage}"
            PRODUCT_TABLE_NAME: "Product-${self:custom.environmentVars.${self:provider.stage}.STAGE_CODE}-${self:provider.stage}"
            MODIFIER_GROUP_TABLE_NAME: "ModifierGroup-${self:custom.environmentVars.${self:provider.stage}.STAGE_CODE}-${self:provider.stage}"
            MODIFIER_TABLE_NAME: "Modifier-${self:custom.environmentVars.${self:provider.stage}.STAGE_CODE}-${self:provider.stage}"
            CATEGORY_PRODUCT_LINK_TABLE_NAME: "CategoryProductLink-${self:custom.environmentVars.${self:provider.stage}.STAGE_CODE}-${self:provider.stage}"
            PRODUCT_MODIFIER_GROUP_LINK_TABLE_NAME: "ProductModifierGroupLink-${self:custom.environmentVars.${self:provider.stage}.STAGE_CODE}-${self:provider.stage}"
            MODIFIER_GROUP_MODIFIER_LINK_TABLE_NAME: "ModifierGroupModifierLink-${self:custom.environmentVars.${self:provider.stage}.STAGE_CODE}-${self:provider.stage}"
            INTEGRATION_MAPPING_TABLE_NAME: "IntegrationMapping-${self:custom.environmentVars.${self:provider.stage}.STAGE_CODE}-${self:provider.stage}"
            DOSHII_API_BASE_URL: "https://sandbox.doshii.co/"

    create-order:
        name: integration-create-order-${self:provider.stage}
        handler: src/handlers/createOrder.handler
        timeout: 120
        environment:
            SHIFT8_API_CONFIG_SECRET_ID: "prod/shift8/api_config"
            SHIFT8_API_TOKEN_SECRET_ID: "prod/shift8/api_token"
            SHIFT8_PAYMENT_TYPE_NUMBER: "9972"
            SHIFT8_PAYMENT_MEDIA_NAME: "Kiosk Payment"
            INTEGRATION_MAPPING_TABLE_NAME: "IntegrationMapping-${self:custom.environmentVars.${self:provider.stage}.STAGE_CODE}-${self:provider.stage}"
            SHIFT8_RESPONSE_URL: "https://yez941zubk.execute-api.ap-southeast-2.amazonaws.com/prod/order-response"
            DOSHII_API_BASE_URL: "https://sandbox.doshii.co/"

custom:
    environmentVars:
        dev:
            STAGE_CODE: "ki7ehbmllzgn3lz5np3cuhf5ba"
        test:
            STAGE_CODE: "cuana653qva7jgspa3yvm7vbdu"
        prod:
            STAGE_CODE: "pqeegsouprcnzplpchlsdrlhti"
